const env = (import.meta as any).env || {};

export const CONTRACT_ADDRESSES = {
  CORE: env.VITE_CONTRACT_CORE_ADDR || '0xdB2465BC1F7D148e4078892C9dC679a45CBC03fD',
  TREASURY: env.VITE_CONTRACT_TREASURY_ADDR || '0x4318EC4C34d5D7CB6d73686a5e8514F7BA3e203e',
  REPUTATION: env.VITE_CONTRACT_REPUTATION_ADDR || '0x71cB013F7a4c0C09769Ebfd77b27F080ca147462',
};

export interface CaseData {
  id: string;
  submitter: string;
  media_url: string;
  description: string;
  context_urls: string[];
  initial_side: 'CLAIM_FAKE' | 'CLAIM_REAL';
  created_at: number;
  deadline: number;
  status: 'OPEN' | 'ADJUDICATING' | 'RESOLVED' | 'REFUNDED';
  verdict: 'FAKE' | 'REAL' | 'INCONCLUSIVE' | '';
  verdict_side: 'CLAIM_FAKE' | 'CLAIM_REAL' | 'NONE' | '';
  confidence: number;
  reason: string;
  total_fake: number;
  total_real: number;
}

export const DEMO_MOCK_CASES: CaseData[] = [
  {
    id: 'case-1',
    submitter: '0x71C7656EC7ab88b098defB751B7401B5f6d8976F',
    media_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe',
    description: 'Suspicious photo showing anomalous hand artifacts and digital diffusion halos around background lighting.',
    context_urls: [
      'https://reuters.com/fact-check/sample-deepfake-analysis',
      'https://snopes.com/fact-check/sample-check'
    ],
    initial_side: 'CLAIM_FAKE',
    created_at: Date.now() - 3600000 * 4,
    deadline: Date.now() + 3600000 * 20,
    status: 'OPEN',
    verdict: '',
    verdict_side: '',
    confidence: 0,
    reason: '',
    total_fake: 250000000000000000000,
    total_real: 120000000000000000000
  },
  {
    id: 'case-2',
    submitter: '0x3C44CdD46a935571ed359B09d73d2a7c4a17955F',
    media_url: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab',
    description: 'Claimed audio transcript clip asserting CEO resignation during unannounced board meeting.',
    context_urls: [
      'https://apnews.com/article/press-release-verification'
    ],
    initial_side: 'CLAIM_REAL',
    created_at: Date.now() - 3600000 * 24,
    deadline: Date.now() - 3600000 * 2,
    status: 'RESOLVED',
    verdict: 'REAL',
    verdict_side: 'CLAIM_REAL',
    confidence: 91,
    reason: 'Verified against official SEC EDGAR filings and matching video stream timestamps from authentic broadcast feeds.',
    total_fake: 50000000000000000000,
    total_real: 350000000000000000000
  },
  {
    id: 'case-3',
    submitter: '0x90F79bf6EB2c4f870365E785982E1f101E93b906',
    media_url: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485',
    description: 'Viral video clip of executive statement allegedly generated by voice cloning tech.',
    context_urls: [
      'https://factcheck.org/2026/executive-audio-claim'
    ],
    initial_side: 'CLAIM_FAKE',
    created_at: Date.now() - 3600000 * 48,
    deadline: Date.now() - 3600000 * 12,
    status: 'RESOLVED',
    verdict: 'FAKE',
    verdict_side: 'CLAIM_FAKE',
    confidence: 94,
    reason: 'Forensic spectrogram analysis identified consistent 16kHz neural synthesis boundary artifacts typical of ElevenLabs v2 voice models.',
    total_fake: 500000000000000000000,
    total_real: 80000000000000000000
  }
];
